In [2]:
import fastbook
fastbook.setup_book()
from fastai.vision.all import *
from fastbook import plot_function

In [1]:
def binary_cross_entropy(inputs, targets):
    inputs = inputs.sigmoid()
    return -torch.where(targets==1, inputs, 1-inputs).log().mean()

In [3]:
torch.random.manual_seed(42)

In [25]:
acts = torch.randn((6,2)) * 2

In [5]:
acts

tensor([[ 0.6734,  0.2576],
        [ 0.4689,  0.4607],
        [-2.2457, -0.3727],
        [ 4.4164, -1.2760],
        [ 0.9233,  0.5347],
        [ 1.0698,  1.6187]])

In [6]:
acts.sigmoid()

tensor([[0.6623, 0.5641],
        [0.6151, 0.6132],
        [0.0957, 0.4079],
        [0.9881, 0.2182],
        [0.7157, 0.6306],
        [0.7446, 0.8346]])

In [27]:
targ = tensor([[0,1],[1,1],[0,0],[1,0],[1,0],[0,0]])

In [41]:
loss = binary_cross_entropy(acts, targ)
loss

tensor(0.6971)

In [29]:
torch.where(targ==1, acts, 1-acts)

tensor([[ 2.5317, -1.5012],
        [ 2.7051,  1.3726],
        [ 1.6555, -0.5899],
        [ 0.5630,  0.8877],
        [ 1.0454,  1.4767],
        [ 1.0998, -0.0527]])

In [30]:
a = torch.where(targ == 1, 1, 0)
a

tensor([[0, 1],
        [1, 1],
        [0, 0],
        [1, 0],
        [1, 0],
        [0, 0]])

In [37]:
loss2 = F.binary_cross_entropy(acts.sigmoid().float(), targ.float())
loss2

tensor(0.6971)

In [40]:
loss3 = F.binary_cross_entropy_with_logits(acts.float(), targ.float())
loss3

tensor(0.6971)