In [1]:
!pip install -Uqq fastai
!pip install -Uqq fastbook

In [37]:
import pandas as pd
from functools import partial


In [3]:
train_org = pd.read_csv("data/titanic/train.csv")

In [4]:
# train_org.drop("Name", axis=1)
df = train_org.drop(columns = ["Name", "PassengerId", "Ticket", "Cabin"], axis=1)


In [5]:
df

Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0           0       3    male  22.0      1      0   7.2500        S
1           1       1  female  38.0      1      0  71.2833        C
2           1       3  female  26.0      0      0   7.9250        S
3           1       1  female  35.0      1      0  53.1000        S
4           0       3    male  35.0      0      0   8.0500        S
..        ...     ...     ...   ...    ...    ...      ...      ...
886         0       2    male  27.0      0      0  13.0000        S
887         1       1  female  19.0      0      0  30.0000        S
888         0       3  female   NaN      1      2  23.4500        S
889         1       1    male  26.0      0      0  30.0000        C
890         0       3    male  32.0      0      0   7.7500        Q

[891 rows x 8 columns]

In [6]:
df = df.dropna(subset=['Age', 'Embarked'])
df = df.reset_index(drop=True)
df = df[df['Fare'] != 0]
df = df.reset_index(drop=True)

In [7]:
df

Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0           0       3    male  22.0      1      0   7.2500        S
1           1       1  female  38.0      1      0  71.2833        C
2           1       3  female  26.0      0      0   7.9250        S
3           1       1  female  35.0      1      0  53.1000        S
4           0       3    male  35.0      0      0   8.0500        S
..        ...     ...     ...   ...    ...    ...      ...      ...
700         0       3  female  39.0      0      5  29.1250        Q
701         0       2    male  27.0      0      0  13.0000        S
702         1       1  female  19.0      0      0  30.0000        S
703         1       1    male  26.0      0      0  30.0000        C
704         0       3    male  32.0      0      0   7.7500        Q

[705 rows x 8 columns]

In [8]:
df["Male"] = (df["Sex"] == "male").astype(int)

In [9]:
df

Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked  Male
0           0       3    male  22.0      1      0   7.2500        S     1
1           1       1  female  38.0      1      0  71.2833        C     0
2           1       3  female  26.0      0      0   7.9250        S     0
3           1       1  female  35.0      1      0  53.1000        S     0
4           0       3    male  35.0      0      0   8.0500        S     1
..        ...     ...     ...   ...    ...    ...      ...      ...   ...
700         0       3  female  39.0      0      5  29.1250        Q     0
701         0       2    male  27.0      0      0  13.0000        S     1
702         1       1  female  19.0      0      0  30.0000        S     0
703         1       1    male  26.0      0      0  30.0000        C     1
704         0       3    male  32.0      0      0   7.7500        Q     1

[705 rows x 9 columns]

In [10]:
df["EmbarkedS"] = (df["Embarked"] == "S").astype(int)

In [11]:
df

Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked  Male  \
0           0       3    male  22.0      1      0   7.2500        S     1   
1           1       1  female  38.0      1      0  71.2833        C     0   
2           1       3  female  26.0      0      0   7.9250        S     0   
3           1       1  female  35.0      1      0  53.1000        S     0   
4           0       3    male  35.0      0      0   8.0500        S     1   
..        ...     ...     ...   ...    ...    ...      ...      ...   ...   
700         0       3  female  39.0      0      5  29.1250        Q     0   
701         0       2    male  27.0      0      0  13.0000        S     1   
702         1       1  female  19.0      0      0  30.0000        S     0   
703         1       1    male  26.0      0      0  30.0000        C     1   
704         0       3    male  32.0      0      0   7.7500        Q     1   

     EmbarkedS  
0            1  
1            0  
2            1  
3            1  
4            1  
..         ...  
700          0  
701          1  
702          1  
703          0  
704          0  

[705 rows x 10 columns]

In [12]:
df["EmbarkedC"] = (df["Embarked"] == "C").astype(int)

In [13]:
df

Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked  Male  \
0           0       3    male  22.0      1      0   7.2500        S     1   
1           1       1  female  38.0      1      0  71.2833        C     0   
2           1       3  female  26.0      0      0   7.9250        S     0   
3           1       1  female  35.0      1      0  53.1000        S     0   
4           0       3    male  35.0      0      0   8.0500        S     1   
..        ...     ...     ...   ...    ...    ...      ...      ...   ...   
700         0       3  female  39.0      0      5  29.1250        Q     0   
701         0       2    male  27.0      0      0  13.0000        S     1   
702         1       1  female  19.0      0      0  30.0000        S     0   
703         1       1    male  26.0      0      0  30.0000        C     1   
704         0       3    male  32.0      0      0   7.7500        Q     1   

     EmbarkedS  EmbarkedC  
0            1          0  
1            0          1  
2            1          0  
3            1          0  
4            1          0  
..         ...        ...  
700          0          0  
701          1          0  
702          1          0  
703          0          1  
704          0          0  

[705 rows x 11 columns]

In [14]:
df["Pclass_1"] = (df["Pclass"] == 1).astype(int)
df["Pclass_2"] = (df["Pclass"] == 2).astype(int)

In [15]:
df

Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked  Male  \
0           0       3    male  22.0      1      0   7.2500        S     1   
1           1       1  female  38.0      1      0  71.2833        C     0   
2           1       3  female  26.0      0      0   7.9250        S     0   
3           1       1  female  35.0      1      0  53.1000        S     0   
4           0       3    male  35.0      0      0   8.0500        S     1   
..        ...     ...     ...   ...    ...    ...      ...      ...   ...   
700         0       3  female  39.0      0      5  29.1250        Q     0   
701         0       2    male  27.0      0      0  13.0000        S     1   
702         1       1  female  19.0      0      0  30.0000        S     0   
703         1       1    male  26.0      0      0  30.0000        C     1   
704         0       3    male  32.0      0      0   7.7500        Q     1   

     EmbarkedS  EmbarkedC  Pclass_1  Pclass_2  
0            1          0         0         0  
1            0          1         1         0  
2            1          0         0         0  
3            1          0         1         0  
4            1          0         0         0  
..         ...        ...       ...       ...  
700          0          0         0         0  
701          1          0         0         1  
702          1          0         1         0  
703          0          1         1         0  
704          0          0         0         0  

[705 rows x 13 columns]

In [16]:
max_age = df["Age"].max()
max_age
df["AgeN"] = df["Age"] / max_age
df

Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked  Male  \
0           0       3    male  22.0      1      0   7.2500        S     1   
1           1       1  female  38.0      1      0  71.2833        C     0   
2           1       3  female  26.0      0      0   7.9250        S     0   
3           1       1  female  35.0      1      0  53.1000        S     0   
4           0       3    male  35.0      0      0   8.0500        S     1   
..        ...     ...     ...   ...    ...    ...      ...      ...   ...   
700         0       3  female  39.0      0      5  29.1250        Q     0   
701         0       2    male  27.0      0      0  13.0000        S     1   
702         1       1  female  19.0      0      0  30.0000        S     0   
703         1       1    male  26.0      0      0  30.0000        C     1   
704         0       3    male  32.0      0      0   7.7500        Q     1   

     EmbarkedS  EmbarkedC  Pclass_1  Pclass_2    AgeN  
0            1          0         0         0  0.2750  
1            0          1         1         0  0.4750  
2            1          0         0         0  0.3250  
3            1          0         1         0  0.4375  
4            1          0         0         0  0.4375  
..         ...        ...       ...       ...     ...  
700          0          0         0         0  0.4875  
701          1          0         0         1  0.3375  
702          1          0         1         0  0.2375  
703          0          1         1         0  0.3250  
704          0          0         0         0  0.4000  

[705 rows x 14 columns]

In [17]:
import numpy as np
df['log_Fare'] = np.log(df['Fare'])
df

Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked  Male  \
0           0       3    male  22.0      1      0   7.2500        S     1   
1           1       1  female  38.0      1      0  71.2833        C     0   
2           1       3  female  26.0      0      0   7.9250        S     0   
3           1       1  female  35.0      1      0  53.1000        S     0   
4           0       3    male  35.0      0      0   8.0500        S     1   
..        ...     ...     ...   ...    ...    ...      ...      ...   ...   
700         0       3  female  39.0      0      5  29.1250        Q     0   
701         0       2    male  27.0      0      0  13.0000        S     1   
702         1       1  female  19.0      0      0  30.0000        S     0   
703         1       1    male  26.0      0      0  30.0000        C     1   
704         0       3    male  32.0      0      0   7.7500        Q     1   

     EmbarkedS  EmbarkedC  Pclass_1  Pclass_2    AgeN  log_Fare  
0            1          0         0         0  0.2750  1.981001  
1            0          1         1         0  0.4750  4.266662  
2            1          0         0         0  0.3250  2.070022  
3            1          0         1         0  0.4375  3.972177  
4            1          0         0         0  0.4375  2.085672  
..         ...        ...       ...       ...     ...       ...  
700          0          0         0         0  0.4875  3.371597  
701          1          0         0         1  0.3375  2.564949  
702          1          0         1         0  0.2375  3.401197  
703          0          1         1         0  0.3250  3.401197  
704          0          0         0         0  0.4000  2.047693  

[705 rows x 15 columns]

In [23]:
x_df = df[["SibSp", "Parch", "Male", "EmbarkedS", "EmbarkedC", "Pclass_1", "Pclass_2", "AgeN", "log_Fare"]].copy()
x_df["Ones"] = 1
x_df

SibSp  Parch  Male  EmbarkedS  EmbarkedC  Pclass_1  Pclass_2    AgeN  \
0        1      0     1          1          0         0         0  0.2750   
1        1      0     0          0          1         1         0  0.4750   
2        0      0     0          1          0         0         0  0.3250   
3        1      0     0          1          0         1         0  0.4375   
4        0      0     1          1          0         0         0  0.4375   
..     ...    ...   ...        ...        ...       ...       ...     ...   
700      0      5     0          0          0         0         0  0.4875   
701      0      0     1          1          0         0         1  0.3375   
702      0      0     0          1          0         1         0  0.2375   
703      0      0     1          0          1         1         0  0.3250   
704      0      0     1          0          0         0         0  0.4000   

     log_Fare  Ones  
0    1.981001     1  
1    4.266662     1  
2    2.070022     1  
3    3.972177     1  
4    2.085672     1  
..        ...   ...  
700  3.371597     1  
701  2.564949     1  
702  3.401197     1  
703  3.401197     1  
704  2.047693     1  

[705 rows x 10 columns]

In [24]:
y_df = df[["Survived"]].copy()
y_df

Survived
0           0
1           1
2           1
3           1
4           0
..        ...
700         0
701         0
702         1
703         1
704         0

[705 rows x 1 columns]

In [30]:
def f(a, x): 
    return a * x

In [26]:
x_array = x_df.values
# tensor
x = torch.tensor(x_array)
x

tensor([[1.0000, 0.0000, 1.0000,  ..., 0.2750, 1.9810, 1.0000],
        [1.0000, 0.0000, 0.0000,  ..., 0.4750, 4.2667, 1.0000],
        [0.0000, 0.0000, 0.0000,  ..., 0.3250, 2.0700, 1.0000],
        ...,
        [0.0000, 0.0000, 0.0000,  ..., 0.2375, 3.4012, 1.0000],
        [0.0000, 0.0000, 1.0000,  ..., 0.3250, 3.4012, 1.0000],
        [0.0000, 0.0000, 1.0000,  ..., 0.4000, 2.0477, 1.0000]],
       dtype=torch.float64)

In [28]:
# tensor
y = torch.tensor(y_df.values)
# y

In [88]:
def mae(preds, acts): return (torch.abs(preds-acts)).mean()

def make_fx(a):
    return partial(f, a)

def fx_mae(a):
    f = make_fx(a)
    return mae(f(x), y)



In [66]:
import torch
a = torch.rand(10) - 0.5

a.requires_grad_()
a

tensor([ 0.0372,  0.0734, -0.2460, -0.3111,  0.0007, -0.2165, -0.3260, -0.1643,
         0.4352, -0.2246], requires_grad=True)

In [67]:
loss = fx_mae(a)

In [68]:
loss.backward()

In [69]:
a.grad

tensor([ 0.0113,  0.0003, -0.0633, -0.0776, -0.0040, -0.0257, -0.0245, -0.0370,
         0.2731, -0.1000])

In [70]:
loss

tensor(0.5398, dtype=torch.float64, grad_fn=<MeanBackward0>)

In [83]:
for i in range(10):
    loss = fx_mae(a)
    loss.backward()
    with torch.no_grad(): a -= a.grad*0.01
    # if i % 10 == 0:
    print(f'step={i}; loss={loss:.2f} ')
    # print(a.grad)
    # print(a)

step=0; loss=1.42 
step=1; loss=1.42 
step=2; loss=1.41 
step=3; loss=1.41 
step=4; loss=1.40 
step=5; loss=1.39 
step=6; loss=1.38 
step=7; loss=1.37 
step=8; loss=1.35 
step=9; loss=1.34 


# Lets try with 2 liner functions and summing them
`f(x) = ax + bx`

First we create random a and b

In [84]:
a = torch.rand(10) - 0.5
a.requires_grad_()
b = torch.rand(10) - 0.5
b.requires_grad_()
print(a)
print(b)

tensor([-0.1203,  0.1869,  0.3659,  0.4339, -0.3090, -0.3916, -0.3334,  0.0499,
        -0.3713, -0.0140], requires_grad=True)
tensor([-0.0573,  0.1717,  0.0562, -0.3079,  0.1286,  0.4080,  0.1788, -0.0241,
        -0.3805,  0.1850], requires_grad=True)


Then we create function `f(x) = a*x + b*x`

In [90]:
def f2(a,b,x):
    return a*x + b*x

def make_fx2(a, b):
    return partial(f2, a, b)

def fx_mae2(a, b):
    f2 = make_fx2(a, b)
    return mae(f2(x), y)

Test manually

In [91]:
loss = fx_mae2(a,b)
loss.backward()
print(loss)
print(a.grad)
print(b.grad)

tensor(0.6711, dtype=torch.float64, grad_fn=<MeanBackward0>)
tensor([-0.0519,  0.0043,  0.0372,  0.0209, -0.0184, -0.0084, -0.0245,  0.0083,
        -0.3002,  0.0186])
tensor([-0.0519,  0.0043,  0.0372,  0.0209, -0.0184, -0.0084, -0.0245,  0.0083,
        -0.3002,  0.0186])


Test in loop

In [95]:
for i in range(10):
    loss = fx_mae2(a,b)
    loss.backward()
    with torch.no_grad(): 
        a -= a.grad*0.01
        b -= b.grad*0.01
    # if i % 10 == 0:
    print(f'step={i}; loss={loss:.2f} ')
    # print(a.grad)
    # print(a)

step=0; loss=0.44 
step=1; loss=0.43 
step=2; loss=0.43 
step=3; loss=0.45 
step=4; loss=0.47 
step=5; loss=0.50 
step=6; loss=0.52 
step=7; loss=0.54 
step=8; loss=0.56 
step=9; loss=0.58 


Lets try with 5 params

In [100]:
a = torch.rand(10) - 0.5
a.requires_grad_()
b = torch.rand(10) - 0.5
b.requires_grad_()
c = torch.rand(10) - 0.5
c.requires_grad_()
d = torch.rand(10) - 0.5
d.requires_grad_()
e = torch.rand(10) - 0.5
e.requires_grad_()


def f5(a,b,c,d,e,x):
    return a*x + b*x + c*x + d*x + e*x

def make_fx5(a, b, c, d, e):
    return partial(f5, a, b, c, d, e)

def fx_mae5(a, b, c, d, e):
    f5 = make_fx5(a, b, c, d, e)
    return mae(f5(x), y)

In [104]:
for i in range(10):
    loss = fx_mae5(a,b,c,d,e)
    loss.backward()
    with torch.no_grad(): 
        a -= a.grad*0.001
        b -= b.grad*0.001
        c -= c.grad*0.001
        d -= d.grad*0.001
        e -= e.grad*0.001
    # if i % 10 == 0:
    print(f'step={i}; loss={loss:.2f} ')
    # print(a.grad)
    # print(a)

step=0; loss=0.49 
step=1; loss=0.49 
step=2; loss=0.49 
step=3; loss=0.49 
step=4; loss=0.49 
step=5; loss=0.49 
step=6; loss=0.49 
step=7; loss=0.49 
step=8; loss=0.49 
step=9; loss=0.49 


Lets try with n params

In [179]:
an = []
for i in range(10000):
    a = torch.rand(10) - 0.5
    # a = a.unsqueeze(1)
    a.requires_grad_()
    an.append(a)

def f_n(an,x):
    val = sum(value * x for value in an)
    mask = val < 0
    val[mask] = 0
    # print(val)
    # if val < 0:
    #     val = 0
    return val

def make_fx_n(an):
    return partial(f_n, an)

def fx_mae_n(an):
    fn = make_fx_n(an)
    return mae(fn(x), y)

# for a in an:
#     print(a)

In [167]:
loss = fx_mae_n(an)
loss.backward()
print(loss)
print(an[0].grad)
print(an[1].grad)
# for a in an:
#     print(a)

tensor([[0.0755, 0.0000, 0.0000,  ..., 0.1309, 2.3017, 0.0000],
        [0.0755, 0.0000, 0.0000,  ..., 0.2261, 4.9573, 0.0000],
        [0.0000, 0.0000, 0.0000,  ..., 0.1547, 2.4051, 0.0000],
        ...,
        [0.0000, 0.0000, 0.0000,  ..., 0.1130, 3.9517, 0.0000],
        [0.0000, 0.0000, 0.0000,  ..., 0.1547, 3.9517, 0.0000],
        [0.0000, 0.0000, 0.0000,  ..., 0.1904, 2.3791, 0.0000]],
       dtype=torch.float64, grad_fn=<IndexPutBackward0>)
tensor(0.6987, dtype=torch.float64, grad_fn=<MeanBackward0>)
tensor([0.0113, 0.0000, 0.0000, 0.0209, 0.0184, 0.0257, 0.0000, 0.0083, 0.3002,
        0.0000])
tensor([0.0113, 0.0000, 0.0000, 0.0209, 0.0184, 0.0257, 0.0000, 0.0083, 0.3002,
        0.0000])


In [185]:
for i in range(10):
    loss = fx_mae_n(an)
    loss.backward()
    with torch.no_grad(): 
        for value in an:
            value -= value.grad*0.001 
            # print(value)
    print(f'step={i}; loss={loss:.2f} ')

step=0; loss=0.40 
step=1; loss=0.40 
step=2; loss=0.40 
step=3; loss=0.40 
step=4; loss=0.40 
step=5; loss=0.40 
step=6; loss=0.40 
step=7; loss=0.41 
step=8; loss=0.41 
step=9; loss=0.41 


In [142]:
print(an[195:])

[tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], requires_grad=True), tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], requires_grad=True), tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], requires_grad=True), tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], requires_grad=True), tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], requires_grad=True)]


## Some testing with tensor computation


In [154]:
a = torch.tensor([1,2,3])
# b = torch.tensor([[1], [2], [3]])
# a * b
b = a.unsqueeze(1)
b

tensor([[1],
        [2],
        [3]])